
name: build_xl2roefact_cli_app
on:
  push:
    branches:
      - build-xl2roefact
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Build xl2roefact CLI application
        run: |
          cd xl2roefact
          python -m pip install --upgrade pip
          pip install setuptools --upgrade
          
          #   install PDM and build environment
          python -m pip install pdm
          python -m pdm install
          python -m pdm run build_all
          
          #    commit work done and push it back to server (attn!!!, here you are on client machine of GitHub organization)
          git commit -am "Automated site built"
          git push





      
