
name: run_xl2roefact_cli_app
run-name: Automated `xl2roefact` test-run (by RENware Software Systems)
on:
  push:
    branches:
      - test-xl2roefact
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Run xl2roefact CLI application
        run: |
          cd xl2roefact
          python -m pip install --upgrade pip
          pip install setuptools --upgrade
          
          #   install PDM and build environment
          python -m pip install pdm
          python -m pdm install
          python -m pdm run xl2roefact xl2json -d ./tests 2>./tests/_test_results.txt
          
          #    commit work done and push it back to server (attn!!!, here you are on client machine of GitHub organization)
          git add tests/*
          git commit -am "Automated `xl2roefact` test-run (by RENware Software Systems)"
          git push





      
